apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-pvc
  namespace: build-something-william
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: hostpath